// Ambient types for the wasm-bindgen glue generated by `scripts/build-wasm.sh`
// into this directory. The actual `.js` and `.wasm` are git-ignored build
// artifacts; this declaration lets the extension typecheck without them.

export function optimize(request_json: string): string;

export default function init(
  module_or_path?: string | URL | Request | Response | BufferSource | WebAssembly.Module
): Promise<unknown>;
